sudo: required
services:
  - docker

before_install:
  - docker build -t warunakanishka/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true warunakanishka/react-test npm test

after_success:
  - docker build -t warunakanishka/multi-client  ./client
  - docker build -t warunakanishka/multi-nginx  ./nginx
  - docker build -t warunakanishka/multi-server  ./server
  - docker build -t warunakanishka/multi-worker  ./worker
  # docker login
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push warunakanishka/multi-client
  - docker push warunakanishka/multi-nginx
  - docker push warunakanishka/multi-server
  - docker push warunakanishka/multi-worker

